name: Build directory2podcast
on: [push, pull_request]
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Set up golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: go build .
  